[tools]
bun = "latest"

[tasks.dev]
run = "bun run --watch src/index.ts"

[tasks.install-deps]
run = "bun install"

[tasks.lint]
run = "bunx @biomejs/biome lint"

[tasks.run]
run = "bun run src/index.ts"

[tasks.test]
run = "bun test"

[tasks.build]
run = 'docker buildx build . --load -t journal-downloads:{{arg(name="docker_image_tag", default="latest")}}'

[tasks.generate-link]
run = 'bun run src/generateDownloadLink.ts --url "{{ option(name="url") }}" --host "{{ option(name="host") }}" --filename "{{ option(name="filename") }}"'
