[tools]
bun = "latest"

[tasks.dev]
run = "bun run --watch src/index.ts"

[tasks.run]
run = "bun run src/index.ts"

[tasks.test]
run = "bun test"

[tasks.build]
run = 'docker buildx build . --load -t journal-downloads:{{arg(name="docker_image_tag", default="latest")}}'
